name: Update Monero CLI

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run update script
        run: |
          bash update-monero.sh

      - name: Commit and push updated binary
        run: |
          git config user.name "monero-bot"
          git config user.email "monero-bot@example.com"
          git add monero
          git commit -m "Update Monero CLI to latest version" || echo "No changes to commit"
          git push
